<script>
    import { Chart, Card, A, Button, Dropdown, DropdownItem, Popover, Tooltip } from 'flowbite-svelte';
    import { InfoCircleSolid, ArrowDownToBraketSolid, ChevronDownSolid, ChevronRightSolid, PenSolid, DownloadSolid, ShareNodesSolid } from 'flowbite-svelte-icons';
    import { Modal } from 'flowbite-svelte';
    import TaskTable from './TaskTable.svelte';
    let defaultModal = false;
    let isOpen = false;
    
    const childTasks = [{
                            taskId : 2,
                            taskName : "Task 2",
                            deadline : new Date(20-12-2002),
                            progress : 90
                        },
                        {
                            taskId : 3,
                            taskName : "Task 3",
                            deadline : new Date(20-12-2002),
                            progress : 80
                        },
                        {
                            taskId : 4,
                            taskName : "Task 4",
                            deadline : new Date(20-12-2002),
                            progress : 70
                        },
                        {
                            taskId : 5,
                            taskName : "Task 5",
                            deadline : new Date(20-12-2002),
                            progress : 85
                        }
                    ];
    const parentTask = {
        taskId : 5,
        taskName : "Task 5",
        deadline : new Date(20-12-2002),
        progress : 30
    };

    const lenOfSubTask = childTasks.length;
    function randomColor() {
  // Generate random values for red, green, and blue between 0 and 255
  const r = Math.floor(Math.random() * 256);
  const g = Math.floor(Math.random() * 256);
  const b = Math.floor(Math.random() * 256);

  // Create a hex string representing the color
  const hexColor = `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`;

  return hexColor;
}
    let progressList = [];
    let randomColors = [];
    let labelTask = [];

    for (const object of childTasks) {
        progressList.push(object.progress);
        randomColors.push(randomColor());
        labelTask.push(object.taskName);
    }

    const options = {
      //series: [90, 85, 70],
      series : [...progressList],
      //colors: ['#1C64F2', '#16BDCA', '#FDBA8C'],
      colors : [...randomColors],
      chart: {
        height: '100%',
        width: '100%',
        type: 'radialBar',
        sparkline: {
          enabled: true
        }
      },
      plotOptions: {
        radialBar: {
          track: {
            background: '#E5E7EB'
          },
          dataLabels: {
            show: false
          },
          hollow: {
            margin: 0,
            size: '32%'
          }
        }
      },
      grid: {
        show: false,
        strokeDashArray: 4,
        padding: {
          left: 2,
          right: 2,
          top: -23,
          bottom: -20
        }
      },
      //labels: ['Done', 'In progress', 'To do'],
      labels : [...labelTask],
      legend: {
        show: true,
        position: 'bottom',
        fontFamily: 'Inter, sans-serif'
      },
      tooltip: {
        enabled: true,
        x: {
          show: false
        }
      },
      yaxis: {
        show: false,
        labels: {
          formatter: function (value) {
            return value + '%';
          }
        }
      }
    };


  </script>
  
  <Card class='w-full'>
    <div class="flex justify-between items-start w-full">
      <div class="flex-col items-center">
        <div class="flex items-center mb-1">
          <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white me-1">Task progress</h5>
          <InfoCircleSolid id="donut1" class="w-3.5 h-3.5 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white cursor-pointer ms-1" />
          <!-- <Popover triggeredBy="#donut1" class="text-sm text-gray-500 bg-white border border-gray-200 rounded-lg shadow-sm w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400 z-10">
            <div class="p-3 space-y-2">
              <h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
              <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
              <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
              <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
              <A href="/">Read more <ChevronRightSolid class="w-2 h-2 ms-1.5" /></A>
            </div>
          </Popover> -->
        </div>
      </div>
      <!-- <div class="flex justify-end items-center">
        <ArrowDownToBraketSolid class="w-3.5 h-3.5" />
        <Tooltip>Download CSV</Tooltip>
      </div> -->
    </div>
  
    <div class="bg-gray-50 dark:bg-gray-700 p-3 rounded-lg">
      <div class="grid grid-cols-3 gap-3 mb-2">
        {#each childTasks as child}
        <dl class="bg-orange-50 dark:bg-gray-600 rounded-lg flex flex-col items-center justify-center h-[78px]">
            <dt class="w-8 h-8 rounded-full bg-orange-100 dark:bg-gray-500 text-orange-600 dark:text-orange-300 text-sm font-medium flex items-center justify-center mb-1">{child.progress}%</dt>
            <dd class="text-orange-600 dark:text-orange-300 text-sm font-medium">{child.taskName} </dd>
        </dl>
        {/each}
        <!-- <dl class="bg-orange-50 dark:bg-gray-600 rounded-lg flex flex-col items-center justify-center h-[78px]">
          <dt class="w-8 h-8 rounded-full bg-orange-100 dark:bg-gray-500 text-orange-600 dark:text-orange-300 text-sm font-medium flex items-center justify-center mb-1">12</dt>
          <dd class="text-orange-600 dark:text-orange-300 text-sm font-medium">To do</dd>
        </dl>
        <dl class="bg-teal-50 dark:bg-gray-600 rounded-lg flex flex-col items-center justify-center h-[78px]">
          <dt class="w-8 h-8 rounded-full bg-teal-100 dark:bg-gray-500 text-teal-600 dark:text-teal-300 text-sm font-medium flex items-center justify-center mb-1">23</dt>
          <dd class="text-teal-600 dark:text-teal-300 text-sm font-medium">In progress</dd>
        </dl>
        <dl class="bg-blue-50 dark:bg-gray-600 rounded-lg flex flex-col items-center justify-center h-[78px]">
          <dt class="w-8 h-8 rounded-full bg-blue-100 dark:bg-gray-500 text-blue-600 dark:text-blue-300 text-sm font-medium flex items-center justify-center mb-1">64</dt>
          <dd class="text-blue-600 dark:text-blue-300 text-sm font-medium">Done</dd>
        </dl> -->
      </div>
      <button on:click={() => (isOpen = !isOpen)} type="button" class="hover:underline text-xs text-gray-500 dark:text-gray-400 font-medium inline-flex items-center">Show more details <ChevronDownSolid class="w-2 h-2 ms-1" /> </button>
      {#if isOpen}
        <div id="more-details" class="border-gray-200 border-t dark:border-gray-600 pt-3 mt-3 space-y-2">
          <dl class="flex items-center justify-between">
            <dt class="text-gray-500 dark:text-gray-400 text-sm font-normal">Average task completion rate:</dt>
            <dd class="bg-green-100 text-green-800 text-xs font-medium inline-flex items-center px-2.5 py-1 rounded-md dark:bg-green-900 dark:text-green-300">
              <svg class="w-2.5 h-2.5 me-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13V1m0 0L1 5m4-4 4 4" />
              </svg> {parentTask.progress}%
            </dd>
          </dl>
          <dl class="flex items-center justify-between">
            <dt class="text-gray-500 dark:text-gray-400 text-sm font-normal">Days until deadline:</dt>
            <dd class="bg-gray-100 text-gray-800 text-xs font-medium inline-flex items-center px-2.5 py-1 rounded-md dark:bg-gray-600 dark:text-gray-300">13 days</dd>
          </dl>
          <!-- <dl class="flex items-center justify-between">
            <dt class="text-gray-500 dark:text-gray-400 text-sm font-normal">Next meeting:</dt>
            <dd class="bg-gray-100 text-gray-800 text-xs font-medium inline-flex items-center px-2.5 py-1 rounded-md dark:bg-gray-600 dark:text-gray-300">Thursday</dd>
          </dl> -->
        </div>
      {/if}
    </div>
  
    <Chart {options}  />
  
    <div class="grid grid-col-1 items-center border-gray-200 border-t dark:border-gray-700 justify-between">
      <!-- <div class="flex justify-between items-center pt-5"> -->
        <!-- <Button class="text-sm font-medium text-gray-500 dark:text-gray-400 hover:text-gray-900 text-center inline-flex items-center dark:hover:text-white bg-transparent hover:bg-transparent dark:bg-transparent dark:hover:bg-transparent focus:ring-transparent dark:focus:ring-transparent py-0">Last 7 days<ChevronDownSolid class="w-2.5 m-2.5 ms-1.5" /></Button>
        <Dropdown class="w-40" offset="-6">
          <DropdownItem>Yesterday</DropdownItem>
          <DropdownItem>Today</DropdownItem>
          <DropdownItem>Last 7 days</DropdownItem>
          <DropdownItem>Last 30 days</DropdownItem>
          <DropdownItem>Last 90 days</DropdownItem>
        </Dropdown> -->
        <!-- <A href="/" class="uppercase text-sm font-semibold hover:text-primary-700 dark:hover:text-primary-500 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700 px-3 py-2 hover:no-underline">
          View Task Table -->
         
          <Button on:click={() => (defaultModal = true)}>View Task List</Button>
          <Modal title="Tasks List" bind:open={defaultModal} autoclose>
            <TaskTable />
            <!-- <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">With less than a month to go before the European Union enacts new consumer privacy laws for its citizens, companies around the world are updating their terms of service agreements to comply.</p>
            <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">The European Union’s General Data Protection Regulation (G.D.P.R.) goes into effect on May 25 and is meant to ensure a common set of data rights in the European Union. It requires organizations to notify users as soon as possible of high-risk data breaches that could personally affect them.</p> -->
            <!-- <svelte:fragment slot="footer">
              <Button on:click={() => alert('Handle "success"')}>I accept</Button>
              <Button color="alternative">Decline</Button>
            </svelte:fragment> -->
          </Modal>
          
          <!-- <ChevronRightSolid class="w-2.5 h-2.5 ms-1.5" /> -->
        
      <!-- </div> -->
    </div>
  </Card>


 
  
  